### ISSUE TITLE
autoprefixer 没有生成厂商前缀

### ISSUE THREAD

**Issue by springwq** [springwq/about-me#1]
@happypeter , 试了好久，autoprefixer 就是无法生成厂商前缀。
- 对普通 CSS 文件，单独只用 autoprefixer 也生成不了前缀。
- 全局安装 gulp-autoprefixer, 也不行。

https://github.com/springwq/about-me/tree/gh-pages

**Comment by springwq** [comment]
原来是 autoprefixer 对不需要前缀的元素就补生成前缀了，比如 
```css
color: red
```
 而像
```css
 display: flex
``` 
 就生成了

**Comment by happypeter** [comment]
是这样的。
